######################################################################
# Automatically generated by qmake (3.0) Tue Feb 14 15:51:35 2017
######################################################################

TEMPLATE = app
TARGET = MessageBox
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
