######################################################################
# Automatically generated by qmake (3.0) Tue Feb 14 12:18:01 2017
######################################################################

TEMPLATE = app
TARGET = VBox
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
