######################################################################
# Automatically generated by qmake (3.0) Tue Feb 14 17:14:20 2017
######################################################################

TEMPLATE = app
TARGET = ProgressBar
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h Thread.h
SOURCES += main.cpp MyDlg.cpp Thread.cpp
