######################################################################
# Automatically generated by qmake (3.0) Tue Feb 14 18:22:05 2017
######################################################################

TEMPLATE = app
TARGET = FindDialog
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += FindDlg.h
SOURCES += FindDlg.cpp main.cpp
