######################################################################
# Automatically generated by qmake (3.0) Tue Feb 14 10:43:12 2017
######################################################################

TEMPLATE = app
TARGET = HBox
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
