######################################################################
# Automatically generated by qmake (3.0) Tue Feb 14 12:43:45 2017
######################################################################

TEMPLATE = app
TARGET = Box
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h MyHBoxLayout.h
SOURCES += main.cpp MyDlg.cpp
