######################################################################
# Automatically generated by qmake (3.0) Tue Feb 14 15:24:52 2017
######################################################################

TEMPLATE = app
TARGET = StackedLayout
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += GridDlg.h HBoxDlg.h MyDlg.h VBoxDlg.h
SOURCES += GridDlg.cpp HBoxDlg.cpp main.cpp MyDlg.cpp VBoxDlg.cpp
