######################################################################
# Automatically generated by qmake (3.0) Tue Feb 14 14:37:24 2017
######################################################################

TEMPLATE = app
TARGET = SignalsAndSlots
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
