######################################################################
# Automatically generated by qmake (3.0) Tue Feb 14 17:48:49 2017
######################################################################

TEMPLATE = app
TARGET = OneSignalWithMultipleSlots
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
