######################################################################
# Automatically generated by qmake (3.0) Tue Feb 14 16:44:34 2017
######################################################################

TEMPLATE = app
TARGET = Threads
INCLUDEPATH += .

# Input
HEADERS += Thread.h
SOURCES += main.cpp Thread.cpp
